<?php

namespace testBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MyentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyentityRepository extends EntityRepository
{
}
