<?php

namespace testBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * test_symfonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class test_symfonyRepository extends EntityRepository
{
}
