testBundle\Entity\Reservation:
    type: entity
    table: null
    repositoryClass: testBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }

    manyToMany:
        passengers:
            targetEntity: User
            mappedBy: reservation