terrain_index:
    path:     /
    defaults: { _controller: "testBundle:Terrain:index" }
    methods:  GET

terrain_show:
    path:     /{id}/show
    defaults: { _controller: "testBundle:Terrain:show" }
    methods:  GET

terrain_new:
    path:     /new
    defaults: { _controller: "testBundle:Terrain:new" }
    methods:  [GET, POST]

terrain_edit:
    path:     /{id}/edit
    defaults: { _controller: "testBundle:Terrain:edit" }
    methods:  [GET, POST]

terrain_delete:
    path:     /{id}/delete
    defaults: { _controller: "testBundle:Terrain:delete" }
    methods:  DELETE
