test_symfony_index:
    path:     /
    defaults: { _controller: "testBundle:test_symfony:index" }
    methods:  GET

test_symfony_show:
    path:     /{id}/show
    defaults: { _controller: "testBundle:test_symfony:show" }
    methods:  GET

test_symfony_new:
    path:     /new
    defaults: { _controller: "testBundle:test_symfony:new" }
    methods:  [GET, POST]

test_symfony_edit:
    path:     /{id}/edit
    defaults: { _controller: "testBundle:test_symfony:edit" }
    methods:  [GET, POST]

test_symfony_delete:
    path:     /{id}/delete
    defaults: { _controller: "testBundle:test_symfony:delete" }
    methods:  DELETE
